# Mod Settings
mod.name = "G'lek's Utility Library"
mod.id = gleks_utility_library
mod.author = "G'lek Tarssza"
mod.description = "A collection of common code used in G'lek's Minecraft mods."
mod.version = 0.1.0
mod.homepage = https://github.com/glektarssza/minecraft-gleks-utility-library
mod.credits = "The GTNH Team for RetroFuturaGradle, G'lek Tarssza for the mod itself."
mod.base_group = com.glektarssza
mod.archive_base_name = gleks-utility-library-forge
mod.dependencies =
mod.version.accepted_save_range = [0.1.0,0.2.0)
mod.version.accepted_remote_range = [0.1.0,0.2.0)
mod.sided_proxy.client_side = com.glektarssza.utility_library.ClientProxy
mod.sided_proxy.server_side = com.glektarssza.utility_library.ServerProxy
mod.gui_factory =
mod.update_manifest_url = https://github.com/glektarssza/minecraft-gleks-utility-library/raw/branch/main/forgeUpdateManifest.json
mod.signature =
mod.mixins.enabled = true
mod.mixins.hot_swap.enabled = true

# Minecraft Settings
minecraft.version = 1.7.10
minecraft.version.range = [1.7.10,1.12.0)

# Java Settings
java.compiler.file.encoding = UTF-8

# Gradle Settings
org.gradle.caching = true
org.gradle.configuration-cache = true
